# TCL File Generated by Component Editor 17.0
# Fri Feb 09 13:10:30 MST 2018
# DO NOT MODIFY


# 
# Synthesizer "Synthesizer" v1.0
#  2018.02.09.13:10:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Synthesizer
# 
set_module_property DESCRIPTION ""
set_module_property NAME Synthesizer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Synthesizer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SynthesizerTopLevel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SynthesizerTopLevel.vhd VHDL PATH SynthesizerTopLevel.vhd TOP_LEVEL_FILE
add_fileset_file SynthesizerPackage.vhd VHDL PATH SynthesizerPackage.vhd
add_fileset_file Synthesizer.vhd VHDL PATH Synthesizer.vhd
add_fileset_file SinLut.vhd VHDL PATH SinLut.vhd
add_fileset_file AddressIncrementor.vhd VHDL PATH AddressIncrementor.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point phase_increments_voice0
# 
add_interface phase_increments_voice0 avalon end
set_interface_property phase_increments_voice0 addressUnits WORDS
set_interface_property phase_increments_voice0 associatedClock clock_sink
set_interface_property phase_increments_voice0 associatedReset reset
set_interface_property phase_increments_voice0 bitsPerSymbol 8
set_interface_property phase_increments_voice0 burstOnBurstBoundariesOnly false
set_interface_property phase_increments_voice0 burstcountUnits WORDS
set_interface_property phase_increments_voice0 explicitAddressSpan 0
set_interface_property phase_increments_voice0 holdTime 0
set_interface_property phase_increments_voice0 linewrapBursts false
set_interface_property phase_increments_voice0 maximumPendingReadTransactions 0
set_interface_property phase_increments_voice0 maximumPendingWriteTransactions 0
set_interface_property phase_increments_voice0 readLatency 0
set_interface_property phase_increments_voice0 readWaitTime 1
set_interface_property phase_increments_voice0 setupTime 0
set_interface_property phase_increments_voice0 timingUnits Cycles
set_interface_property phase_increments_voice0 writeWaitTime 0
set_interface_property phase_increments_voice0 ENABLED true
set_interface_property phase_increments_voice0 EXPORT_OF ""
set_interface_property phase_increments_voice0 PORT_NAME_MAP ""
set_interface_property phase_increments_voice0 CMSIS_SVD_VARIABLES ""
set_interface_property phase_increments_voice0 SVD_ADDRESS_GROUP ""

add_interface_port phase_increments_voice0 avs_write_n_phase_increments_voice0 write_n Input 1
add_interface_port phase_increments_voice0 avs_writedata_phase_increments_voice0 writedata Input 32
set_interface_assignment phase_increments_voice0 embeddedsw.configuration.isFlash 0
set_interface_assignment phase_increments_voice0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment phase_increments_voice0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment phase_increments_voice0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink_1
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 32
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source aso_data_audio_out data Output 32
add_interface_port avalon_streaming_source aso_valid_audio_out valid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink csi_clk50M clk Input 1


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 csi_clk32k clk Input 1

