	soc_system u0 (
		.audio_0_external_interface_ADCDAT                (<connected-to-audio_0_external_interface_ADCDAT>),                //                  audio_0_external_interface.ADCDAT
		.audio_0_external_interface_ADCLRCK               (<connected-to-audio_0_external_interface_ADCLRCK>),               //                                            .ADCLRCK
		.audio_0_external_interface_BCLK                  (<connected-to-audio_0_external_interface_BCLK>),                  //                                            .BCLK
		.audio_0_external_interface_DACDAT                (<connected-to-audio_0_external_interface_DACDAT>),                //                                            .DACDAT
		.audio_0_external_interface_DACLRCK               (<connected-to-audio_0_external_interface_DACLRCK>),               //                                            .DACLRCK
		.audio_and_video_config_0_external_interface_SDAT (<connected-to-audio_and_video_config_0_external_interface_SDAT>), // audio_and_video_config_0_external_interface.SDAT
		.audio_and_video_config_0_external_interface_SCLK (<connected-to-audio_and_video_config_0_external_interface_SCLK>), //                                            .SCLK
		.button_0_external_connection_export              (<connected-to-button_0_external_connection_export>),              //                button_0_external_connection.export
		.button_1_external_connection_export              (<connected-to-button_1_external_connection_export>),              //                button_1_external_connection.export
		.button_2_external_connection_export              (<connected-to-button_2_external_connection_export>),              //                button_2_external_connection.export
		.button_3_external_connection_export              (<connected-to-button_3_external_connection_export>),              //                button_3_external_connection.export
		.clk_clk                                          (<connected-to-clk_clk>),                                          //                                         clk.clk
		.hps_io_hps_io_emac1_inst_TX_CLK                  (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),                  //                                      hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0                    (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),                    //                                            .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1                    (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),                    //                                            .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2                    (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),                    //                                            .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3                    (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),                    //                                            .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0                    (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),                    //                                            .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO                    (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),                    //                                            .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                     (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                     //                                            .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL                  (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),                  //                                            .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL                  (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),                  //                                            .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK                  (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),                  //                                            .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1                    (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),                    //                                            .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2                    (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),                    //                                            .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3                    (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),                    //                                            .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD                      (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                      //                                            .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                       (<connected-to-hps_io_hps_io_sdio_inst_D0>),                       //                                            .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                       (<connected-to-hps_io_hps_io_sdio_inst_D1>),                       //                                            .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                      (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                      //                                            .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                       (<connected-to-hps_io_hps_io_sdio_inst_D2>),                       //                                            .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                       (<connected-to-hps_io_hps_io_sdio_inst_D3>),                       //                                            .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                       (<connected-to-hps_io_hps_io_usb1_inst_D0>),                       //                                            .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                       (<connected-to-hps_io_hps_io_usb1_inst_D1>),                       //                                            .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                       (<connected-to-hps_io_hps_io_usb1_inst_D2>),                       //                                            .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                       (<connected-to-hps_io_hps_io_usb1_inst_D3>),                       //                                            .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                       (<connected-to-hps_io_hps_io_usb1_inst_D4>),                       //                                            .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                       (<connected-to-hps_io_hps_io_usb1_inst_D5>),                       //                                            .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                       (<connected-to-hps_io_hps_io_usb1_inst_D6>),                       //                                            .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                       (<connected-to-hps_io_hps_io_usb1_inst_D7>),                       //                                            .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                      (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                      //                                            .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                      (<connected-to-hps_io_hps_io_usb1_inst_STP>),                      //                                            .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                      (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                      //                                            .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                      (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                      //                                            .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                     (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                     //                                            .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI                    (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),                    //                                            .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO                    (<connected-to-hps_io_hps_io_spim1_inst_MISO>),                    //                                            .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                     (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                     //                                            .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                      (<connected-to-hps_io_hps_io_uart0_inst_RX>),                      //                                            .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                      (<connected-to-hps_io_hps_io_uart0_inst_TX>),                      //                                            .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                      (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                      //                                            .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                      (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                      //                                            .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                      (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                      //                                            .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                      (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                      //                                            .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),                   //                                            .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),                   //                                            .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),                   //                                            .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO48                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),                   //                                            .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),                   //                                            .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),                   //                                            .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61                   (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),                   //                                            .hps_io_gpio_inst_GPIO61
		.memory_mem_a                                     (<connected-to-memory_mem_a>),                                     //                                      memory.mem_a
		.memory_mem_ba                                    (<connected-to-memory_mem_ba>),                                    //                                            .mem_ba
		.memory_mem_ck                                    (<connected-to-memory_mem_ck>),                                    //                                            .mem_ck
		.memory_mem_ck_n                                  (<connected-to-memory_mem_ck_n>),                                  //                                            .mem_ck_n
		.memory_mem_cke                                   (<connected-to-memory_mem_cke>),                                   //                                            .mem_cke
		.memory_mem_cs_n                                  (<connected-to-memory_mem_cs_n>),                                  //                                            .mem_cs_n
		.memory_mem_ras_n                                 (<connected-to-memory_mem_ras_n>),                                 //                                            .mem_ras_n
		.memory_mem_cas_n                                 (<connected-to-memory_mem_cas_n>),                                 //                                            .mem_cas_n
		.memory_mem_we_n                                  (<connected-to-memory_mem_we_n>),                                  //                                            .mem_we_n
		.memory_mem_reset_n                               (<connected-to-memory_mem_reset_n>),                               //                                            .mem_reset_n
		.memory_mem_dq                                    (<connected-to-memory_mem_dq>),                                    //                                            .mem_dq
		.memory_mem_dqs                                   (<connected-to-memory_mem_dqs>),                                   //                                            .mem_dqs
		.memory_mem_dqs_n                                 (<connected-to-memory_mem_dqs_n>),                                 //                                            .mem_dqs_n
		.memory_mem_odt                                   (<connected-to-memory_mem_odt>),                                   //                                            .mem_odt
		.memory_mem_dm                                    (<connected-to-memory_mem_dm>),                                    //                                            .mem_dm
		.memory_oct_rzqin                                 (<connected-to-memory_oct_rzqin>),                                 //                                            .oct_rzqin
		.photodiode_0_conduit_end_export0                 (<connected-to-photodiode_0_conduit_end_export0>),                 //                    photodiode_0_conduit_end.export0
		.photodiode_0_conduit_end_export1                 (<connected-to-photodiode_0_conduit_end_export1>),                 //                                            .export1
		.photodiode_0_conduit_end_export2                 (<connected-to-photodiode_0_conduit_end_export2>),                 //                                            .export2
		.photodiode_0_conduit_end_export3                 (<connected-to-photodiode_0_conduit_end_export3>),                 //                                            .export3
		.photodiode_0_conduit_end_export4                 (<connected-to-photodiode_0_conduit_end_export4>),                 //                                            .export4
		.photodiode_0_conduit_end_export5                 (<connected-to-photodiode_0_conduit_end_export5>),                 //                                            .export5
		.photodiode_0_conduit_end_export6                 (<connected-to-photodiode_0_conduit_end_export6>),                 //                                            .export6
		.photodiode_0_conduit_end_export7                 (<connected-to-photodiode_0_conduit_end_export7>),                 //                                            .export7
		.pll_0_outclk0_clk                                (<connected-to-pll_0_outclk0_clk>),                                //                               pll_0_outclk0.clk
		.red_leds_external_connection_export              (<connected-to-red_leds_external_connection_export>),              //                red_leds_external_connection.export
		.reset_reset_n                                    (<connected-to-reset_reset_n>),                                    //                                       reset.reset_n
		.switches_external_connection_export              (<connected-to-switches_external_connection_export>),              //                switches_external_connection.export
		.character_lcd_0_external_interface_DATA          (<connected-to-character_lcd_0_external_interface_DATA>),          //          character_lcd_0_external_interface.DATA
		.character_lcd_0_external_interface_ON            (<connected-to-character_lcd_0_external_interface_ON>),            //                                            .ON
		.character_lcd_0_external_interface_BLON          (<connected-to-character_lcd_0_external_interface_BLON>),          //                                            .BLON
		.character_lcd_0_external_interface_EN            (<connected-to-character_lcd_0_external_interface_EN>),            //                                            .EN
		.character_lcd_0_external_interface_RS            (<connected-to-character_lcd_0_external_interface_RS>),            //                                            .RS
		.character_lcd_0_external_interface_RW            (<connected-to-character_lcd_0_external_interface_RW>)             //                                            .RW
	);

